sudo: required
language: php
php:
  - "5.6"
services:
  - docker
before_install:
#  - sudo apt-get install pdftk
#  - pdftk
  - php is_dir.php
install:
  - composer install
before_script:
  - php is_dir.php
script: 
  - ls
  - php main.php
after_script:
  - php is_dir.php
