sudo: required
language: php
php:
  - "5.6"
services:
  - docker
before_install:
#  - sudo apt-get install pdftk
  - composer --version
  - composer require mikehaertl/php-shellcommand
#  - pdftk
  - php main.php
